development:
  adapter: mysql
  encoding: utf8
  database: dev_iskhound
  username: root
  password: qwe123
  port: 3306

production:
  adapter: mysql
  encoding: utf8
  host: <%= JSON.parse( ENV['VCAP_SERVICES'] )['mysql-5.1'].first['credentials']['hostname'] rescue 'localhost' %>
  port: <%= JSON.parse( ENV['VCAP_SERVICES'] )['mysql-5.1'].first['credentials']['port'] rescue 3306 %>
  database: <%= JSON.parse( ENV['VCAP_SERVICES'] )['mysql-5.1'].first['credentials']['name'] rescue '' %>
  username: <%= JSON.parse( ENV['VCAP_SERVICES'] )['mysql-5.1'].first['credentials']['username'] rescue '' %>
  password: <%= JSON.parse( ENV['VCAP_SERVICES'] )['mysql-5.1'].first['credentials']['password'] rescue '' %> 